### ISSUE TITLE
Controls getting messed up

### ISSUE THREAD

**Issue by EusthEnoptEron** [EusthEnoptEron/arise-multiplayer#32]
> happened during the optional dragon fight where the demo area is

**Comment by EusthEnoptEron** [comment]
The issue here seems to be that the cameras get out of sync, resulting in the directions not matching anymore.

**Comment by JudyTuesday** [comment]
I've actually been having this happen a lot with my partner. Almost every time I run the game actually. It's gotten so much worse over time, and I'm not sure why lol

**Comment by EusthEnoptEron** [comment]
@JudyTuesday
Got a notification of your message before you deleted it -- would be great if you could give me some details in what way your controls get jumbled.

I have yet to play in multiplayer myself, so I'm completely dependent on feedback to find bugs.
