### ISSUE TITLE
P2 - P4 have to hold the change target button instead of tapping it

### ISSUE THREAD

**Issue by Renevark** [EusthEnoptEron/arise-multiplayer#56]
Players 2 through 4 need to hold the change target button and manually choose their target or hold the button for a moment until the game halts, then release to acquire the nearest target. Tapping the button quickly only seems to work for player 1.

**Comment by EusthEnoptEron** [comment]
Thanks for letting me know.
Should be fixed with [1.0.0-rc.4](https://github.com/EusthEnoptEron/arise-multiplayer/releases/tag/1.0.0-rc.4).
