### ISSUE TITLE
Quick switch for p2-4

### ISSUE THREAD

**Issue by naotocc** [EusthEnoptEron/arise-multiplayer#57]
Really wish i could switch characters in battle like p1, but even through menu doesn't work, any plans to try and make that happen

**Comment by EusthEnoptEron** [comment]
Hm... if there's enough demand, *maybe*.

If you want to change characters during battle, simply reorder them in the battle menu according [to this graphic](https://github.com/EusthEnoptEron/arise-multiplayer/raw/main/Assets/PlayerSlots.jpg). That should work.

**Comment by naotocc** [comment]
but the problem is target button + direction does nothing for p2, same for pressing it on menu where it rotates the characters, cannot change characters if ur not p1

**Comment by EusthEnoptEron** [comment]
Yeah, pressing the direction button only passes on the flag, which only has an effect for P1. You have to change the order. (Although I'd love to make this work a bit more intuitively.)

Here's an example how I changed characters as P2:
https://user-images.githubusercontent.com/800140/147934622-25bf6769-5fbc-4ca0-b743-c486945efda5.mp4

**Comment by naotocc** [comment]
Oh i see, yea the only reason id even want quickswitch is because im used to their slots for boost strike

**Comment by EusthEnoptEron** [comment]
Quick switching should now be possible in the latest release.
