### ISSUE TITLE
Camera stays P1 focused, if P2 is not assigned

### ISSUE THREAD

**Issue by Dyddye** [EusthEnoptEron/arise-multiplayer#74]
Early in the game, you can assign the characters that way, that P2 is not assigned. Then in battle, the camera only focuses P1. If multiple players are available, the camera should show all their positions, regardless of the assignment.

- P1, P3
- P1, P4
- P1, P3, P4

**Comment by EusthEnoptEron** [comment]
Ah, now I understand -- you were talking about the character order. You could always just switch characters during battle and save the assignments by enabling the corresponding flag in the multiplayer mod config; that way you don't have to rearrange the players at all.
