### ISSUE TITLE
Camera is only following player 1.

### ISSUE THREAD

**Issue by gadgetmawombo** [EusthEnoptEron/arise-multiplayer#78]
Started the game from beginning. Playing a new file. Get to first non tutorial battle with 2 players and the camera only follow p1. I can control both characters fine, but the camera only follow 1.

**Comment by gadgetmawombo** [comment]
Im on the latest version. Was there an EVEN newer version that messed up this mod again?

**Comment by EusthEnoptEron** [comment]
Did you move the second character away from the second (=left) slot?

If so, then that's the problem (and has been fixed in the main branch but I haven't bothered creating a release yet.)

**Comment by gadgetmawombo** [comment]
Yes, I had them as player 3. And since there were no other characters, it
happened.
