### ISSUE TITLE
PS4 support?

### ISSUE THREAD

**Issue by madelson** [EusthEnoptEron/arise-multiplayer#85]
I assume the answer is “no”, but do you know of any way this mod can be used on a PS4 console?

**Comment by EusthEnoptEron** [comment]
Yep, sadly the answer is no.
If you're in it for the couch co-op (and own a PC), I recommend getting a long HDMI cable (which is what we're doing) or using in-home streaming, and pairing your PS4 gamepads to the PC.

*In theory*, it might be possible to create a version of the mod that works for the PS4, but that would require a lot of work and expertise that I do not have.
