### ISSUE TITLE
Concerning steam link compatibility

### ISSUE THREAD

**Issue by donny110** [EusthEnoptEron/arise-multiplayer#88]
If I run this on pc with the unreal mod loader and then try to use the steam link on my pc downstairs to play this on the couch as I usually do, my controller will not do anything.. And sadly I can't connect them to pc and reach it down stairs... The Xbox controller won't reach that without major lag 😅.. Is there something I can do to fix this or is there a fix to this at all or am I just out of luck here, I usually play this with my partner and the fact this game was apparently no longer couch Co op really really saddened me, so I was super hyped when I saw this mod, sadly haven't been able to get it to work for my use case.. Excuse the long write up.. But, long story short.. compatibility with the steam link, any chance of getting that to work? And if it already is, how?

**Comment by EusthEnoptEron** [comment]
Hey there,

As long as Steam recognizes the controllers, the mod should work.
In fact, I just tried it using Steam In-Home Streaming and Steam Link, and both worked.

In the case of Steam Link, one of my gamepads was detected twice. To fix this, I pressed F2 (in the menu, outside of battle), and disabled the superfluous controller via Drag & Drop.

Things I suggest you could try:

1. Check if the mod works without Steam Link / In-Home Streaming. For a quick test to see if the mod was installed correctly, press "F2" and see if a menu pops up.
2. If the mod works locally, try the F2 menu while connected through Steam Link, and if there's an issue, fix it as described above.
3. Keep in mind that multiplayer won't work in tutorial fights. ;-)

**Comment by donny110** [comment]
I am utterly unsure what caused it to not work, but the next day.. I set it up with a fresh mind and used the f2 thing to check.. and just as last time.. it did show on desktop but now ALSO on the steam link version.. And it all worked flawlessly! Thank you so much for the great help here and oh boi am I enjoying this mod now!
